CFLAGS = -Wall -g

#all: ex19
#all: newgameFinal
all: newgame

newgame: newgameFinal
#newgameFinal: newgame.o
#ex19: object.o

clean:
	#rm -f ex19
	#rm -f object.o
	rm -f newgameFinal
	rm -f newgame.o
